const $=s=>document.querySelector(s); let stores=[],prices=[],options=[];
const API=(window.KD_API_BASE||'').replace(/\/$/,'');
Promise.all([fetch('data/stores.json').then(r=>r.json()),fetch('data/prices.json').then(r=>r.json()),fetch('data/options.json').then(r=>r.json())]).then(([s,p,o])=>{stores=s;prices=p;options=o;$('#status').textContent=`店舗 ${stores.length}件 / 検証済み料金 ${prices.length}件`;}).catch(e=>$('#status').innerHTML=`<div class="error">データ読込失敗: ${esc(e.message)}</div>`);
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function minutes(t){return t.split(':').reduce((a,b)=>a*60+Number(b),0)}
function validTime(p,startMin,dur){if(p.start_time==null)return true; const a=minutes(p.start_time),b=minutes(p.end_time||'23:59'); return startMin>=a && startMin<b;}
function choosePlan(s){const people=Number($('#people').value),dur=Number($('#duration').value),customer=$('#customer').value,day=$('#day').value;let ps=prices.filter(p=>p.store_id===s.id&&p.day_type===day&&['student_member',customer].includes(p.customer_type)&&Number.isFinite(p.price_yen)); if(!ps.length) return null;
  const packs=ps.filter(p=>['pack','free_time'].includes(p.plan_type)&&p.duration_minutes>=dur).sort((a,b)=>a.price_yen-b.price_yen);
  const units=ps.filter(p=>p.plan_type==='thirty_min').sort((a,b)=>a.price_yen-b.price_yen);
  const candidates=[]; if(packs[0])candidates.push({...packs[0],calc_price:packs[0].price_yen}); if(units[0])candidates.push({...units[0],calc_price:units[0].price_yen*Math.ceil(dur/30)}); if(!candidates.length)return null; return candidates.sort((a,b)=>a.calc_price-b.calc_price)[0];
}
function optionCost(s,type,people){if(!$('#'+type).checked)return {cost:0,known:true,label:''}; const list=options.filter(o=>o.store_id===s.id&&o.type===type); if(!list.length)return {cost:0,known:false,label:'料金確認中'};const o=list[0];if(o.mode==='unavailable')return {cost:0,known:true,label:'なし'};if(o.price_yen==null)return {cost:0,known:false,label:'料金確認中'};let cost=o.per_person?o.price_yen*people:o.price_yen;if(o.mode==='double_for_even'&&people%2===0)cost=o.price_yen*(people/2);return {cost,known:true,label:o.label||o.mode};}
async function geocode(q){const u=API+'/api/geocode'; if(API){const r=await fetch(u+'?q='+encodeURIComponent(q));if(!r.ok)throw Error('出発地点を検索できませんでした');return r.json();} const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q='+encodeURIComponent(q),{headers:{'Accept-Language':'ja'}});if(!r.ok)throw Error('地図検索に失敗');const a=await r.json();if(!a.length)throw Error('出発地点が見つかりません');return {lat:Number(a[0].lat),lon:Number(a[0].lon),label:a[0].display_name};}
async function route(origin,s){if(s.latitude==null||s.longitude==null)return {known:false,minutes:0,distanceKm:0,cost:0}; if($('#mode').value==='transit'){if(API){const r=await fetch(API+'/api/route?mode=transit&origin_lat='+origin.lat+'&origin_lon='+origin.lon+'&dest_lat='+s.latitude+'&dest_lon='+s.longitude);if(r.ok)return await r.json();}return {known:false,minutes:0,distanceKm:0,cost:0,transitUrl:`https://www.google.com/maps/dir/?api=1&origin=${origin.lat},${origin.lon}&destination=${s.latitude},${s.longitude}&travelmode=transit`};}
 const profile=$('#mode').value==='car'?'driving':'foot';const u=API?`${API}/api/route?mode=${profile}&origin_lat=${origin.lat}&origin_lon=${origin.lon}&dest_lat=${s.latitude}&dest_lon=${s.longitude}`:`https://router.project-osrm.org/route/v1/${profile}/${origin.lon},${origin.lat};${s.longitude},${s.latitude}?overview=false`;const r=await fetch(u);if(!r.ok)return {known:false,minutes:0,distanceKm:0,cost:0};const x=await r.json();if(API)return x;return {known:true,minutes:(x.routes[0].duration/60),distanceKm:x.routes[0].distance/1000,cost:$('#mode').value==='car'?(x.routes[0].distance/1000)*20:0};}
async function compare(){if(!stores.length)return;$('#status').textContent='出発地点を検索中…';let origin;try{origin=await geocode($('#origin').value);}catch(e){$('#status').innerHTML=`<div class="error">${esc(e.message)}</div>`;return}const out=[];const day=$('#day').value;for(const s of stores){const plan=choosePlan(s);if(!plan)continue;let rt=await route(origin,s);const pc=optionCost(s,'potato',Number($('#people').value)),ac=optionCost(s,'alcohol',Number($('#people').value));const people=Number($('#people').value),travelRound=rt.minutes*2,totalTime=Number($('#duration').value)+travelRound;const karaokeTotal=plan.calc_price*people;const travelTotal=$('#includeTravelCost').checked?rt.cost*2:0;const total=karaokeTotal+pc.cost+ac.cost+travelTotal;const perHour=total/(people*(totalTime/60));out.push({...s,plan,total,perHour,route:rt,unknown:!rt.known||!pc.known||!ac.known});}out.sort((a,b)=>a.perHour-b.perHour);render(out);}
function render(rows){if(!rows.length){$('#results').innerHTML='<div class="error">現在の料金データで比較できる店舗がありません。GitHub Actionsで公式データ更新を実行してください。</div>';return}const best=rows[0];$('#status').textContent=`比較対象 ${rows.length}店舗（移動時間は往復で加算）`;$('#results').innerHTML=rows.slice(0,30).map((r,i)=>{const close=i>0&&Math.abs(r.perHour-best.perHour)/best.perHour<.1;return `<article class="result"><div class="top"><div><span class="badge">#${i+1} ${r.chain_id}</span><h3>${esc(r.name)}</h3><div class="small">${esc(r.address||'住所未取得')}</div></div><div class="price">${Math.round(r.perHour).toLocaleString()}円/h</div></div><p><b>総額:</b> ${Math.round(r.total).toLocaleString()}円 / ${$('#people').value}人　 <b>プラン:</b> ${esc(r.plan.plan_type)} ${r.plan.duration_minutes}分</p><p>🚶 移動 ${r.route.known?Math.round(r.route.minutes)+'分（片道）':'未取得'}　🚗/🚃 交通費 ${r.route.known?Math.round((r.route.cost||0)*2)+'円':'未取得'}</p><div class="chips"><span class="chip">${esc(r.plan.included||'料金表による')}</span>${r.route.transitUrl?`<a class="chip" target="_blank" href="${r.route.transitUrl}">Google Mapsで経路</a>`:''}</div>${r.unknown?'<div class="warn">一部の移動・追加料金が未取得のため暫定順位。</div>':''}${close&&i>0?'<div class="good">価格差が小さめ。店舗ごとの設備・ポテト・飲み放題・移動時間も見て選ぶのがおすすめ。</div>':''}<p class="small"><a target="_blank" href="${esc(r.source_url)}">公式店舗ページ</a></p></article>`}).join('');}
$('#search').addEventListener('click',compare);
